# Copyright (C) 2011 The Android Open Source Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# Prebuilt libraries that are needed to build open-source libraries
#PRODUCT_COPY_FILES := \
#	vendor/motorola/spyder/lib/libaudio.so:obj/lib/libaudio.so \
#	vendor/motorola/spyder/lib/libcamera.so:obj/lib/libcamera.so \
#	vendor/motorola/spyder/lib/libgps.so:obj/lib/libgps.so


PRODUCT_COPY_FILES += \
	vendor/motorola/spyder/bin/thermaldaemon:system/bin/thermaldaemon \
    vendor/motorola/spyder/bin/ftmipcd:system/bin/ftmipcd \
    vendor/motorola/spyder/bin/syslink_trace_daemon.out:system/bin/syslink_trace_daemon.out \
    vendor/motorola/spyder/bin/dmm_daemontest.out:system/bin/dmm_daemontest.out \
    vendor/motorola/spyder/bin/utilsApp.out:system/bin/utilsApp.out \
    vendor/motorola/spyder/bin/tstmetainfo:system/bin/tstmetainfo \
    vendor/motorola/spyder/bin/ap_gain_france.bin:system/bin/ap_gain_france.bin \
    vendor/motorola/spyder/bin/memtest_mode:system/bin/memtest_mode \
    vendor/motorola/spyder/bin/dvz:system/bin/dvz \
    vendor/motorola/spyder/bin/messageQApp.out:system/bin/messageQApp.out \
    vendor/motorola/spyder/bin/openssl:system/bin/openssl \
    vendor/motorola/spyder/bin/loadpreinstalls.sh:system/bin/loadpreinstalls.sh \
    vendor/motorola/spyder/bin/hdcp-mknod:system/bin/hdcp-mknod \
    vendor/motorola/spyder/bin/tf_daemon:system/bin/tf_daemon \
    vendor/motorola/spyder/bin/event_listener.out:system/bin/event_listener.out \
    vendor/motorola/spyder/bin/Hostapd:system/bin/Hostapd \
    vendor/motorola/spyder/bin/napics.sh:system/bin/napics.sh \
    vendor/motorola/spyder/bin/ducati_load.out:system/bin/ducati_load.out \
    vendor/motorola/spyder/bin/whisperd:system/bin/whisperd \
    vendor/motorola/spyder/bin/slpmresources.out:system/bin/slpmresources.out \
    vendor/motorola/spyder/bin/memmgrserver.out:system/bin/memmgrserver.out \
    vendor/motorola/spyder/bin/d2c_test:system/bin/d2c_test \
    vendor/motorola/spyder/bin/IttiamAacEncoder_Test:system/bin/IttiamAacEncoder_Test \
    vendor/motorola/spyder/bin/smc_pa_ctrl:system/bin/smc_pa_ctrl \
    vendor/motorola/spyder/bin/msp430:system/bin/msp430 \
    vendor/motorola/spyder/bin/syslink_tilertest.out:system/bin/syslink_tilertest.out \
    vendor/motorola/spyder/bin/tcmd:system/bin/tcmd \
    vendor/motorola/spyder/bin/ap_gain_mmul.bin:system/bin/ap_gain_mmul.bin \
    vendor/motorola/spyder/bin/testpppd:system/bin/testpppd \
    vendor/motorola/spyder/bin/sharedRegionApp.out:system/bin/sharedRegionApp.out \
    vendor/motorola/spyder/bin/heapMemMPApp.out:system/bin/heapMemMPApp.out \
    vendor/motorola/spyder/bin/interm3.out:system/bin/interm3.out \
    vendor/motorola/spyder/bin/slpmtest.out:system/bin/slpmtest.out \
    vendor/motorola/spyder/bin/rcm_daemontest.out:system/bin/rcm_daemontest.out \
    vendor/motorola/spyder/bin/bthelp:system/bin/bthelp \
    vendor/motorola/spyder/bin/vpnclientpm:system/bin/vpnclientpm \
    vendor/motorola/spyder/bin/bugtogo.sh:system/bin/bugtogo.sh \
    vendor/motorola/spyder/bin/chat-ril:system/bin/chat-ril \
    vendor/motorola/spyder/bin/.directory:system/bin/.directory \
    vendor/motorola/spyder/bin/gateMPApp.out:system/bin/gateMPApp.out \
    vendor/motorola/spyder/bin/btcmd:system/bin/btcmd \
    vendor/motorola/spyder/bin/nameServerApp.out:system/bin/nameServerApp.out \
    vendor/motorola/spyder/bin/rcm_singletest.out:system/bin/rcm_singletest.out \
    vendor/motorola/spyder/bin/mot_boot_mode:system/bin/mot_boot_mode \
    vendor/motorola/spyder/bin/slpmtransport.out:system/bin/slpmtransport.out \
    vendor/motorola/spyder/bin/enc_mgt_tool:system/bin/enc_mgt_tool \
    vendor/motorola/spyder/bin/charge_only_mode:system/bin/charge_only_mode \
    vendor/motorola/spyder/bin/tty2ttyd:system/bin/tty2ttyd \
    vendor/motorola/spyder/bin/enable_mdm_usb_suspend.sh:system/bin/enable_mdm_usb_suspend.sh \
    vendor/motorola/spyder/bin/tcmdhelp:system/bin/tcmdhelp \
    vendor/motorola/spyder/bin/wrigley-diag.sh:system/bin/wrigley-diag.sh \
    vendor/motorola/spyder/bin/bttest_mot:system/bin/bttest_mot \
    vendor/motorola/spyder/bin/mountosh:system/bin/mountosh \
    vendor/motorola/spyder/bin/dbvc_atvc_property_set:system/bin/dbvc_atvc_property_set \
    vendor/motorola/spyder/bin/pppd-ril:system/bin/pppd-ril \
    vendor/motorola/spyder/bin/JuniperVPNTools:system/bin/JuniperVPNTools \
    vendor/motorola/spyder/bin/dund:system/bin/dund \
    vendor/motorola/spyder/bin/listMPApp.out:system/bin/listMPApp.out \
    vendor/motorola/spyder/bin/usbd:system/bin/usbd \
    vendor/motorola/spyder/bin/fbread:system/bin/fbread \
    vendor/motorola/spyder/bin/rcm_multitest.out:system/bin/rcm_multitest.out \
    vendor/motorola/spyder/bin/motobox:system/bin/motobox \
    vendor/motorola/spyder/bin/ap_gain.bin:system/bin/ap_gain.bin \
    vendor/motorola/spyder/bin/heapBufMPApp.out:system/bin/heapBufMPApp.out \
    vendor/motorola/spyder/bin/tund:system/bin/tund \
    vendor/motorola/spyder/bin/secclkd:system/bin/secclkd \
    vendor/motorola/spyder/bin/notifyping.out:system/bin/notifyping.out \
    vendor/motorola/spyder/bin/rcm_multiclienttest.out:system/bin/rcm_multiclienttest.out \
    vendor/motorola/spyder/bin/syslink_daemon.out:system/bin/syslink_daemon.out \
    vendor/motorola/spyder/bin/gkilogd:system/bin/gkilogd \
    vendor/motorola/spyder/bin/akmd8975:system/bin/akmd8975 \
    vendor/motorola/spyder/bin/modemlog:system/bin/modemlog \
    vendor/motorola/spyder/bin/procMgrApp.out:system/bin/procMgrApp.out \
    vendor/motorola/spyder/bin/rcm_multithreadtest.out:system/bin/rcm_multithreadtest.out \
    vendor/motorola/spyder/bin/ecckeyd:system/bin/ecckeyd \
    vendor/motorola/spyder/bin/startup_smc.sh:system/bin/startup_smc.sh \
    vendor/motorola/spyder/bin/batch:system/bin/batch 
    
PRODUCT_COPY_FILES += \
    vendor/motorola/spyder/etc/ecryptfs.exc:system/etc/ecryptfs.exc \
    vendor/motorola/spyder/etc/motorola/ap_flex_version.txt:system/etc/motorola/ap_flex_version.txt \
    vendor/motorola/spyder/etc/motorola/comm_drv/mmins_cust_emergency_number.hs:system/etc/motorola/comm_drv/mmins_cust_emergency_number.hs \
    vendor/motorola/spyder/etc/motorola/comm_drv/mmins_cust_emergency_number.cfg:system/etc/motorola/comm_drv/mmins_cust_emergency_number.cfg \
    vendor/motorola/spyder/etc/motorola/comm_drv/mmins_telephony.cfg:system/etc/motorola/comm_drv/mmins_telephony.cfg \
    vendor/motorola/spyder/etc/motorola/tcmd/pkiprovision.cfg:system/etc/motorola/tcmd/pkiprovision.cfg \
    vendor/motorola/spyder/etc/motorola/tcmd/cid_template.dat:system/etc/motorola/tcmd/cid_template.dat \
    vendor/motorola/spyder/etc/motorola/12m/cqatest_cfg:system/etc/motorola/12m/cqatest_cfg \
    vendor/motorola/spyder/etc/motorola/12m/key_code_map.txt:system/etc/motorola/12m/key_code_map.txt \
    vendor/motorola/spyder/etc/motorola/12m/tcmd_leds.cfg:system/etc/motorola/12m/tcmd_leds.cfg \
    vendor/motorola/spyder/etc/priority_notifications_config.xml:system/etc/priority_notifications_config.xml \
    vendor/motorola/spyder/etc/mspfirmware/version.txt:system/etc/mspfirmware/version.txt \
    vendor/motorola/spyder/etc/mspfirmware/mspfirmware.bin:system/etc/mspfirmware/mspfirmware.bin \
    vendor/motorola/spyder/etc/VideoEditorLite/mve.ini:system/etc/VideoEditorLite/mve.ini \
    vendor/motorola/spyder/etc/profile:system/etc/profile \
    vendor/motorola/spyder/etc/hdmiSolDefLg.gif:system/etc/hdmiSolDefLg.gif \
    vendor/motorola/spyder/etc/permissions/net.juniper.junos.pulse.placeholder.xml:system/etc/permissions/net.juniper.junos.pulse.placeholder.xml \
    vendor/motorola/spyder/etc/permissions/com.cisco.anyconnect.preload.xml:system/etc/permissions/com.cisco.anyconnect.preload.xml \
    vendor/motorola/spyder/etc/permissions/jcifs-krb5-1.3.12.xml:system/etc/permissions/jcifs-krb5-1.3.12.xml \
    vendor/motorola/spyder/etc/permissions/com.zecter.droid.services.xml:system/etc/permissions/com.zecter.droid.services.xml \
    vendor/motorola/spyder/etc/permissions/com.scalado.android.photoeditor.xml:system/etc/permissions/com.scalado.android.photoeditor.xml \
    vendor/motorola/spyder/etc/permissions/com.google.android.maps.xml:system/etc/permissions/com.google.android.maps.xml \
    vendor/motorola/spyder/etc/permissions/com.scalado.caps.xml:system/etc/permissions/com.scalado.caps.xml \
    vendor/motorola/spyder/etc/permissions/zip4j-1.1.3.xml:system/etc/permissions/zip4j-1.1.3.xml \
    vendor/motorola/spyder/etc/amazon-kindle.properties:system/etc/amazon-kindle.properties \
    vendor/motorola/spyder/etc/smc_android_cfg.ini:system/etc/smc_android_cfg.ini \
    vendor/motorola/spyder/etc/firmware/ap_bt_data.bin:system/etc/firmware/ap_bt_data.bin \
    vendor/motorola/spyder/etc/firmware/fmc_init_1283.2.bts:system/etc/firmware/fmc_init_1283.2.bts \
    vendor/motorola/spyder/etc/firmware/fm_rx_init_1283.2.bts:system/etc/firmware/fm_rx_init_1283.2.bts \
    vendor/motorola/spyder/etc/nuance/vsuite_config.xml:system/etc/nuance/vsuite_config.xml \
    vendor/motorola/spyder/etc/ecryptfs.tab:system/etc/ecryptfs.tab \
    vendor/motorola/spyder/etc/smc_pa_pk_4_8Mb_ipa.bin:system/etc/smc_pa_pk_4_8Mb_ipa.bin \
    vendor/motorola/spyder/etc/backup_targets.csv:system/etc/backup_targets.csv \
    vendor/motorola/spyder/etc/qewl.jar:system/etc/qewl.jar \
    vendor/motorola/spyder/etc/pvplayer.cfg:system/etc/pvplayer.cfg \
    vendor/motorola/spyder/etc/omapcam/SEN2_EE.cfg:system/etc/omapcam/SEN2_EE.cfg \
    vendor/motorola/spyder/etc/omapcam/R8_MVEN002_LD2_ND0_IR0_SH0_FL1_SVEN002_DCCID1039.cfg:system/etc/omapcam/R8_MVEN002_LD2_ND0_IR0_SH0_FL1_SVEN002_DCCID1039.cfg \
    vendor/motorola/spyder/etc/omapcam/module1_cal/cid1039_ov8820_ducati_gamma.bin:system/etc/omapcam/module1_cal/cid1039_ov8820_ducati_gamma.bin \
    vendor/motorola/spyder/etc/omapcam/module1_cal/cid1039_ov8820_ipipe_ee_dcc.bin:system/etc/omapcam/module1_cal/cid1039_ov8820_ipipe_ee_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1_cal/cid1039_ov8820_lsc_interp.bin:system/etc/omapcam/module1_cal/cid1039_ov8820_lsc_interp.bin \
    vendor/motorola/spyder/etc/omapcam/module1_cal/cid1039_ov8820_alg_3a_ae_mms2_dcc.bin:system/etc/omapcam/module1_cal/cid1039_ov8820_alg_3a_ae_mms2_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1_cal/cid1039_ov8820_gbce_sw1_dcc.bin:system/etc/omapcam/module1_cal/cid1039_ov8820_gbce_sw1_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1_cal/cid1039_ov8820_ducati_nsf_ldc.bin:system/etc/omapcam/module1_cal/cid1039_ov8820_ducati_nsf_ldc.bin \
    vendor/motorola/spyder/etc/omapcam/module1_cal/cid1039_ov8820_isif_clamp_dcc.bin:system/etc/omapcam/module1_cal/cid1039_ov8820_isif_clamp_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1_ee/cid1039_ov8820_ducati_gamma.bin:system/etc/omapcam/module1_ee/cid1039_ov8820_ducati_gamma.bin \
    vendor/motorola/spyder/etc/omapcam/module1_ee/cid1039_ov8820_ipipe_ee_dcc.bin:system/etc/omapcam/module1_ee/cid1039_ov8820_ipipe_ee_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1_ee/cid1039_ov8820_lsc_interp.bin:system/etc/omapcam/module1_ee/cid1039_ov8820_lsc_interp.bin \
    vendor/motorola/spyder/etc/omapcam/module1_ee/cid1039_ov8820_ducati_nsf_ldc.bin:system/etc/omapcam/module1_ee/cid1039_ov8820_ducati_nsf_ldc.bin \
    vendor/motorola/spyder/etc/omapcam/module1_ee/cid1039_ov8820_isif_clamp_dcc.bin:system/etc/omapcam/module1_ee/cid1039_ov8820_isif_clamp_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1_rel.bak/cid1039_ov8820_ducati_gamma.bin:system/etc/omapcam/module1_rel.bak/cid1039_ov8820_ducati_gamma.bin \
    vendor/motorola/spyder/etc/omapcam/module1_rel.bak/cid1039_ov8820_ipipe_ee_dcc.bin:system/etc/omapcam/module1_rel.bak/cid1039_ov8820_ipipe_ee_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1_rel.bak/cid1039_ov8820_lsc_interp.bin:system/etc/omapcam/module1_rel.bak/cid1039_ov8820_lsc_interp.bin \
    vendor/motorola/spyder/etc/omapcam/module1_rel.bak/cid1039_ov8820_gbce_sw1_dcc.bin:system/etc/omapcam/module1_rel.bak/cid1039_ov8820_gbce_sw1_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1_rel.bak/cid1039_ov8820_ducati_nsf_ldc.bin:system/etc/omapcam/module1_rel.bak/cid1039_ov8820_ducati_nsf_ldc.bin \
    vendor/motorola/spyder/etc/omapcam/module1_rel.bak/cid1039_ov8820_isif_clamp_dcc.bin:system/etc/omapcam/module1_rel.bak/cid1039_ov8820_isif_clamp_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/R8_MVEN002_LD2_ND0_IR0_SH0_FL1_SVEN002_DCCID1039_CAL.cfg:system/etc/omapcam/R8_MVEN002_LD2_ND0_IR0_SH0_FL1_SVEN002_DCCID1039_CAL.cfg \
    vendor/motorola/spyder/etc/omapcam/R8_MVEN002_LD2_ND0_IR0_SH0_FL1_SVEN002_DCCID1039_EE.cfg:system/etc/omapcam/R8_MVEN002_LD2_ND0_IR0_SH0_FL1_SVEN002_DCCID1039_EE.cfg \
    vendor/motorola/spyder/etc/omapcam/module2_ee/cid1042_mt9m114_sensor_config_dcc.bin:system/etc/omapcam/module2_ee/cid1042_mt9m114_sensor_config_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module2/cid1042_mt9m114_sensor_config_dcc.bin:system/etc/omapcam/module2/cid1042_mt9m114_sensor_config_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/SEN2.cfg:system/etc/omapcam/SEN2.cfg \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_cgs_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_cgs_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_dpc_lut_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_dpc_lut_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_golden_module_calibration.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_golden_module_calibration.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rgb2yuv_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rgb2yuv_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_awb_alg_ti3_tuning.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_awb_alg_ti3_tuning.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_ldc_cfg_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_ldc_cfg_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_h3a_aewb_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_h3a_aewb_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_gbce_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_gbce_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_yuv444_to_yuv422_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_yuv444_to_yuv422_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_gic_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_gic_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_caf_dcc_tuning.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_caf_dcc_tuning.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_nf2_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_nf2_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_hllc_dcc_tuning.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_hllc_dcc_tuning.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_3d_lut_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_3d_lut_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_isif_csc_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_isif_csc_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_saf_dcc_tuning.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_saf_dcc_tuning.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_iss_glbce3_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_iss_glbce3_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_car_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_car_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_iss_vstab_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_iss_vstab_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_ae_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_ae_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_ae_mms2_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_ae_mms2_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_ducati_lsc_2d.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_ducati_lsc_2d.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_affw_dcc_tuning.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_alg_3a_af_affw_dcc_tuning.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_nf1_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_nf1_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_ldc_cac_cfg_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_ldc_cac_cfg_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_vnf_cfg_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_vnf_cfg_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_cid1039_capabilities.bin:system/etc/omapcam/module1.bak/cid1039_cid1039_capabilities.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_dpc_otf.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_dpc_otf.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rgb2rgb_2_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rgb2rgb_2_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_cfai_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_cfai_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_lsc_poly_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_lsc_poly_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_ducati_eff_tun.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_ducati_eff_tun.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_alg_adjust_rgb2rgb_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_alg_adjust_rgb2rgb_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_iss_scene_modes_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_iss_scene_modes_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_iss_lbce_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_iss_lbce_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rgb2rgb_1_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rgb2rgb_1_dcc.bin \
    vendor/motorola/spyder/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rsz_dcc.bin:system/etc/omapcam/module1.bak/cid1039_ov8820_ipipe_rsz_dcc.bin \
    vendor/motorola/spyder/etc/wifi/fw_wlan1281_AP.bin:system/etc/wifi/fw_wlan1281_AP.bin \
    vendor/motorola/spyder/etc/wifi/fw_wlan1281.bin:system/etc/wifi/fw_wlan1281.bin \
    vendor/motorola/spyder/etc/wifi/hostapd.conf.templet:system/etc/wifi/hostapd.conf.templet \
    vendor/motorola/spyder/etc/ppp/peers/pppd-ril.options:system/etc/ppp/peers/pppd-ril.options \
    vendor/motorola/spyder/etc/01_Vendor_ti_omx.cfg:system/etc/01_Vendor_ti_omx.cfg \
    vendor/motorola/spyder/etc/dhcpcd/dhcpcd-hooks/21-wins.conf:system/etc/dhcpcd/dhcpcd-hooks/21-wins.conf \
    vendor/motorola/spyder/etc/dhcpcd/dhcpcd-hooks/23-domain-name.conf:system/etc/dhcpcd/dhcpcd-hooks/23-domain-name.conf \
    vendor/motorola/spyder/etc/smc_pa.ift:system/etc/smc_pa.ift \
    vendor/motorola/spyder/etc/excluded-input-devices.xml:system/etc/excluded-input-devices.xml \
    vendor/motorola/spyder/etc/bluetooth/main.conf:system/etc/bluetooth/main.conf \
    vendor/motorola/spyder/etc/smc_pa_pk_4_ipa.bin:system/etc/smc_pa_pk_4_ipa.bin \
    vendor/motorola/spyder/etc/hdmiSolDefSm.gif:system/etc/hdmiSolDefSm.gif \
    vendor/motorola/spyder/etc/btpan.conf:system/etc/btpan.conf \
    vendor/motorola/spyder/etc/encrypt.tab:system/etc/encrypt.tab \
    vendor/motorola/spyder/etc/bluez/main.conf:system/etc/bluez/main.conf \
    vendor/motorola/spyder/etc/supportedlocales.conf:system/etc/supportedlocales.conf \
    vendor/motorola/spyder/etc/spellchecker/es_ES.dic:system/etc/spellchecker/es_ES.dic \
    vendor/motorola/spyder/etc/spellchecker/fr.aff:system/etc/spellchecker/fr.aff \
    vendor/motorola/spyder/etc/spellchecker/de_DE_frami.aff:system/etc/spellchecker/de_DE_frami.aff \
    vendor/motorola/spyder/etc/spellchecker/es_ES.aff:system/etc/spellchecker/es_ES.aff \
    vendor/motorola/spyder/etc/spellchecker/en_US.aff:system/etc/spellchecker/en_US.aff \
    vendor/motorola/spyder/etc/spellchecker/en_US.dic:system/etc/spellchecker/en_US.dic \
    vendor/motorola/spyder/etc/spellchecker/it_IT.aff:system/etc/spellchecker/it_IT.aff \
    vendor/motorola/spyder/etc/spellchecker/pt_BR.aff:system/etc/spellchecker/pt_BR.aff \
    vendor/motorola/spyder/etc/spellchecker/it_IT.dic:system/etc/spellchecker/it_IT.dic \
    vendor/motorola/spyder/etc/spellchecker/de_DE_frami.dic:system/etc/spellchecker/de_DE_frami.dic \
    vendor/motorola/spyder/etc/spellchecker/pt_BR.dic:system/etc/spellchecker/pt_BR.dic \
    vendor/motorola/spyder/etc/spellchecker/en_GB.aff:system/etc/spellchecker/en_GB.aff \
    vendor/motorola/spyder/etc/spellchecker/fr.dic:system/etc/spellchecker/fr.dic \
    vendor/motorola/spyder/etc/spellchecker/pt_PT.aff:system/etc/spellchecker/pt_PT.aff \
    vendor/motorola/spyder/etc/spellchecker/pt_PT.dic:system/etc/spellchecker/pt_PT.dic \
    vendor/motorola/spyder/etc/spellchecker/en_GB.dic:system/etc/spellchecker/en_GB.dic
    
    
PRODUCT_COPY_FILES += \
	vendor/motorola/spyder/lib/hw/lights.spyder.so:system/lib/hw/lights.spyder.so \
    vendor/motorola/spyder/lib/hw/alsa.default.so:system/lib/hw/alsa.default.so \
    vendor/motorola/spyder/lib/hw/alsa.omap4.so:system/lib/hw/alsa.omap4.so \
    vendor/motorola/spyder/lib/hw/sensorhub.spyder.so:system/lib/hw/sensorhub.spyder.so \
    vendor/motorola/spyder/lib/hw/gps.spyder.so:system/lib/hw/gps.spyder.so \
    vendor/motorola/spyder/lib/hw/overlay.omap4.so:system/lib/hw/overlay.omap4.so \
    vendor/motorola/spyder/lib/hw/acoustics.default.so:system/lib/hw/acoustics.default.so \
    vendor/motorola/spyder/lib/hw/sensors.spyder.so:system/lib/hw/sensors.spyder.so \
    
PRODUCT_COPY_FILES += \
    vendor/motorola/spyder/lib/libomx_avcdec_sharedlibrary.so:system/lib/libomx_avcdec_sharedlibrary.so \
    vendor/motorola/spyder/lib/libstagefright_color_conversion.so:system/lib/libstagefright_color_conversion.so \
    vendor/motorola/spyder/lib/libOMX.ITTIAM.WMA.decode.so:system/lib/libOMX.ITTIAM.WMA.decode.so \
    vendor/motorola/spyder/lib/libdataencrypt_tpa.so:system/lib/libdataencrypt_tpa.so \
    vendor/motorola/spyder/lib/libmtpstack.so:system/lib/libmtpstack.so \
    vendor/motorola/spyder/lib/librds_util.so:system/lib/librds_util.so \
    vendor/motorola/spyder/lib/libOMX.TI.DUCATI1.VIDEO.CAMERA.so:system/lib/libOMX.TI.DUCATI1.VIDEO.CAMERA.so \
    vendor/motorola/spyder/lib/libmoto_qmi_ril.so:system/lib/libmoto_qmi_ril.so \
    vendor/motorola/spyder/lib/libimage_jni.so:system/lib/libimage_jni.so \
    vendor/motorola/spyder/lib/libmotdrm1.so:system/lib/libmotdrm1.so \
    vendor/motorola/spyder/lib/libOMX_Core.so:system/lib/libOMX_Core.so \
    vendor/motorola/spyder/lib/libXmp_jni.so:system/lib/libXmp_jni.so \
    vendor/motorola/spyder/lib/libwbxmlparser.so:system/lib/libwbxmlparser.so \
    vendor/motorola/spyder/lib/libjanus.so:system/lib/libjanus.so \
    vendor/motorola/spyder/lib/libOMX.TI.DUCATI1.VIDEO.DECODER.so:system/lib/libOMX.TI.DUCATI1.VIDEO.DECODER.so \
    vendor/motorola/spyder/lib/libmss.so:system/lib/libmss.so \
    vendor/motorola/spyder/lib/libbt-mp3.so:system/lib/libbt-mp3.so \
    vendor/motorola/spyder/lib/libmoto_netutil.so:system/lib/libmoto_netutil.so \
    vendor/motorola/spyder/lib/moto-ril-multimode.so:system/lib/moto-ril-multimode.so \
    vendor/motorola/spyder/lib/libhdmi.so:system/lib/libhdmi.so \
    vendor/motorola/spyder/lib/egl/libgles1_texture_stream.so:system/lib/egl/libgles1_texture_stream.so \
    vendor/motorola/spyder/lib/egl/libgles2_texture_stream.so:system/lib/egl/libgles2_texture_stream.so \
    vendor/motorola/spyder/lib/egl/libeglinfo.so:system/lib/egl/libeglinfo.so \
    vendor/motorola/spyder/lib/libtpa.so:system/lib/libtpa.so \
    vendor/motorola/spyder/lib/libfmchr.so:system/lib/libfmchr.so \
    vendor/motorola/spyder/lib/libmotdrm1_jni.so:system/lib/libmotdrm1_jni.so \
    vendor/motorola/spyder/lib/libhostapd_client.so:system/lib/libhostapd_client.so \
    vendor/motorola/spyder/lib/libOMX.ITTIAM.AAC.encode.so:system/lib/libOMX.ITTIAM.AAC.encode.so \
    vendor/motorola/spyder/lib/libmot_btpan_jni.so:system/lib/libmot_btpan_jni.so \
    vendor/motorola/spyder/lib/libquicksec.so:system/lib/libquicksec.so \
    vendor/motorola/spyder/lib/libdlnaprofileparser.so:system/lib/libdlnaprofileparser.so \
    vendor/motorola/spyder/lib/plugins/com.adobe.flashplayer/libysshared.so:system/lib/plugins/com.adobe.flashplayer/libysshared.so \
    vendor/motorola/spyder/lib/plugins/com.adobe.flashplayer/libstagefright_froyo.so:system/lib/plugins/com.adobe.flashplayer/libstagefright_froyo.so \
    vendor/motorola/spyder/lib/plugins/com.adobe.flashplayer/libflashplayer.so:system/lib/plugins/com.adobe.flashplayer/libflashplayer.so \
    vendor/motorola/spyder/lib/plugins/com.adobe.flashplayer/libstagefright_honeycomb.so:system/lib/plugins/com.adobe.flashplayer/libstagefright_honeycomb.so \
    vendor/motorola/spyder/lib/libopencore_downloadreg.so:system/lib/libopencore_downloadreg.so \
    vendor/motorola/spyder/lib/libprojectM.so:system/lib/libprojectM.so \
    vendor/motorola/spyder/lib/libmediaext.so:system/lib/libmediaext.so \
    vendor/motorola/spyder/lib/libomx_arcomxcore_sharedlibrary.so:system/lib/libomx_arcomxcore_sharedlibrary.so \
    vendor/motorola/spyder/lib/libmirror.so:system/lib/libmirror.so \
    vendor/motorola/spyder/lib/libOMX.TI.DUCATI1.MISC.SAMPLE.so:system/lib/libOMX.TI.DUCATI1.MISC.SAMPLE.so \
    vendor/motorola/spyder/lib/libpanorama_jni.so:system/lib/libpanorama_jni.so \
    vendor/motorola/spyder/lib/libmot_bluetooth_jni.so:system/lib/libmot_bluetooth_jni.so \
    vendor/motorola/spyder/lib/libOMX.TI.DUCATI1.VIDEO.MPEG4E.so:system/lib/libOMX.TI.DUCATI1.VIDEO.MPEG4E.so \
    vendor/motorola/spyder/lib/libbt-mpeg12pl.so:system/lib/libbt-mpeg12pl.so \
    vendor/motorola/spyder/lib/libdlnahttpjni.so:system/lib/libdlnahttpjni.so \
    vendor/motorola/spyder/lib/libOMX.TI.DUCATI1.VIDEO.H264D.so:system/lib/libOMX.TI.DUCATI1.VIDEO.H264D.so \
    vendor/motorola/spyder/lib/libOMX.TI.DUCATI1.VIDEO.VP7D.so:system/lib/libOMX.TI.DUCATI1.VIDEO.VP7D.so \
    vendor/motorola/spyder/lib/libnmea.so:system/lib/libnmea.so \
    vendor/motorola/spyder/lib/libttssynthproxy.so:system/lib/libttssynthproxy.so \
    vendor/motorola/spyder/lib/libOMX.TI.DUCATI1.VIDEO.MPEG4D.so:system/lib/libOMX.TI.DUCATI1.VIDEO.MPEG4D.so \
    vendor/motorola/spyder/lib/libdevicestats.so:system/lib/libdevicestats.so \
    vendor/motorola/spyder/lib/libdataencrypt_utils.so:system/lib/libdataencrypt_utils.so \
    vendor/motorola/spyder/lib/libarcomx_evrcdec_sharedlibrary.so:system/lib/libarcomx_evrcdec_sharedlibrary.so \
    vendor/motorola/spyder/lib/libomx_aacdec_sharedlibrary.so:system/lib/libomx_aacdec_sharedlibrary.so \
    vendor/motorola/spyder/lib/libipsec.so:system/lib/libipsec.so \
    vendor/motorola/spyder/lib/libomx_sharedlibrary.so:system/lib/libomx_sharedlibrary.so \
    vendor/motorola/spyder/lib/libscalado.so:system/lib/libscalado.so \
    vendor/motorola/spyder/lib/libsensorhub_jni.so:system/lib/libsensorhub_jni.so \
    vendor/motorola/spyder/lib/libcapsjava.so:system/lib/libcapsjava.so \
    vendor/motorola/spyder/lib/libOMX_CoreOsal.so:system/lib/libOMX_CoreOsal.so \
    vendor/motorola/spyder/lib/libhdcp.so:system/lib/libhdcp.so \
    vendor/motorola/spyder/lib/libfm_stack.so:system/lib/libfm_stack.so \
    vendor/motorola/spyder/lib/libbt-aptx.so:system/lib/libbt-aptx.so \
    vendor/motorola/spyder/lib/libsysmgr.so:system/lib/libsysmgr.so \
    vendor/motorola/spyder/lib/libtimemmgr.so:system/lib/libtimemmgr.so \
    vendor/motorola/spyder/lib/libglwtanijni.so:system/lib/libglwtanijni.so \
    vendor/motorola/spyder/lib/librcm.so:system/lib/librcm.so \
    vendor/motorola/spyder/lib/libopencore_player.so:system/lib/libopencore_player.so \
    vendor/motorola/spyder/lib/libopencore_download.so:system/lib/libopencore_download.so \
    vendor/motorola/spyder/lib/libusbcameraadapter.so:system/lib/libusbcameraadapter.so \
    vendor/motorola/spyder/lib/libvsuite_mot_vs40_cmb.so:system/lib/libvsuite_mot_vs40_cmb.so \
    vendor/motorola/spyder/lib/libnotify.so:system/lib/libnotify.so \
    vendor/motorola/spyder/lib/libtalk_jni.so:system/lib/libtalk_jni.so \
    vendor/motorola/spyder/lib/libarcaudiogetinfo.so:system/lib/libarcaudiogetinfo.so \
    vendor/motorola/spyder/lib/ducati/Notify_MPUSYS_reroute_Test_Core0.xem3:system/lib/ducati/Notify_MPUSYS_reroute_Test_Core0.xem3 \
    vendor/motorola/spyder/lib/ducati/base_image_app_m3.xem3:system/lib/ducati/base_image_app_m3.xem3 \
    vendor/motorola/spyder/lib/libprovlib.so:system/lib/libprovlib.so \
    vendor/motorola/spyder/lib/libssmgr.so:system/lib/libssmgr.so \
    vendor/motorola/spyder/lib/libVendor_ti_omx_config_parser.so:system/lib/libVendor_ti_omx_config_parser.so \
    vendor/motorola/spyder/lib/libtf_crypto_sst.so:system/lib/libtf_crypto_sst.so \
    vendor/motorola/spyder/lib/libreference-cdma-sms.so:system/lib/libreference-cdma-sms.so \
    vendor/motorola/spyder/lib/libphotoflow.so:system/lib/libphotoflow.so \
    vendor/motorola/spyder/lib/libmotodbgutils.so:system/lib/libmotodbgutils.so \
    vendor/motorola/spyder/lib/libril_rds.so:system/lib/libril_rds.so \
    vendor/motorola/spyder/lib/libarcstagefright.so:system/lib/libarcstagefright.so \
    vendor/motorola/spyder/lib/libarcomx_qcelpdec_sharedlibrary.so:system/lib/libarcomx_qcelpdec_sharedlibrary.so \
    vendor/motorola/spyder/lib/libmot_bthid_jni.so:system/lib/libmot_bthid_jni.so \
    vendor/motorola/spyder/lib/libopencore_common.so:system/lib/libopencore_common.so \
    vendor/motorola/spyder/lib/libvideoeditorlite.so:system/lib/libvideoeditorlite.so \
    vendor/motorola/spyder/lib/libWVphoneAPI.so:system/lib/libWVphoneAPI.so \
    vendor/motorola/spyder/lib/libOMX.TI.DUCATI1.IMAGE.JPEGD.so:system/lib/libOMX.TI.DUCATI1.IMAGE.JPEGD.so \
    vendor/motorola/spyder/lib/libskiagl.so:system/lib/libskiagl.so \
    vendor/motorola/spyder/lib/libOMX.TI.DUCATI1.VIDEO.H264E.so:system/lib/libOMX.TI.DUCATI1.VIDEO.H264E.so \
    vendor/motorola/spyder/lib/libopencore_rtsp.so:system/lib/libopencore_rtsp.so \
    vendor/motorola/spyder/lib/libmirrorjni.so:system/lib/libmirrorjni.so \
    vendor/motorola/spyder/lib/libdlnasysjni.so:system/lib/libdlnasysjni.so \
    vendor/motorola/spyder/lib/lib-mot-lte-ril.so:system/lib/lib-mot-lte-ril.so \
    vendor/motorola/spyder/lib/libdmjavaplugin.so:system/lib/libdmjavaplugin.so \
    vendor/motorola/spyder/lib/libvpnclient_jni.so:system/lib/libvpnclient_jni.so \
    vendor/motorola/spyder/lib/libdmengine.so:system/lib/libdmengine.so \
    vendor/motorola/spyder/lib/libnative_renderer.so:system/lib/libnative_renderer.so \
    vendor/motorola/spyder/lib/libbcbmsg.so:system/lib/libbcbmsg.so \
    vendor/motorola/spyder/lib/libui3d.so:system/lib/libui3d.so \
    vendor/motorola/spyder/lib/libpostcapimgproc_intf.so:system/lib/libpostcapimgproc_intf.so \
    vendor/motorola/spyder/lib/libmotintfutil.so:system/lib/libmotintfutil.so \
    vendor/motorola/spyder/lib/libbattd.so:system/lib/libbattd.so \
    vendor/motorola/spyder/lib/libomx_mp3dec_sharedlibrary.so:system/lib/libomx_mp3dec_sharedlibrary.so \
    vendor/motorola/spyder/lib/libomx_rpc.so:system/lib/libomx_rpc.so \
    vendor/motorola/spyder/lib/libmot_atcmd.so:system/lib/libmot_atcmd.so \
    vendor/motorola/spyder/lib/libnativedrm1.so:system/lib/libnativedrm1.so \
    vendor/motorola/spyder/lib/libbabysit.so:system/lib/libbabysit.so \
    vendor/motorola/spyder/lib/libipc.so:system/lib/libipc.so \
    vendor/motorola/spyder/lib/libomx_amrdec_sharedlibrary.so:system/lib/libomx_amrdec_sharedlibrary.so \
    vendor/motorola/spyder/lib/libmcphal.so:system/lib/libmcphal.so \
    vendor/motorola/spyder/lib/libopencore_author.so:system/lib/libopencore_author.so \
    vendor/motorola/spyder/lib/libopencore_mp4localreg.so:system/lib/libopencore_mp4localreg.so \
    vendor/motorola/spyder/lib/libd2cmap.so:system/lib/libd2cmap.so \
    vendor/motorola/spyder/lib/libthermal_config.so:system/lib/libthermal_config.so \
    vendor/motorola/spyder/lib/libarcomx_wmadec_sharedlibrary.so:system/lib/libarcomx_wmadec_sharedlibrary.so \
    vendor/motorola/spyder/lib/libarcplatform.so:system/lib/libarcplatform.so \
    vendor/motorola/spyder/lib/libsyslink_ipc_listener.so:system/lib/libsyslink_ipc_listener.so \
    vendor/motorola/spyder/lib/libmss.so.sig:system/lib/libmss.so.sig \
    vendor/motorola/spyder/lib/libthermal_manager.so:system/lib/libthermal_manager.so \
    vendor/motorola/spyder/lib/libmoto_mdmctrl.so:system/lib/libmoto_mdmctrl.so \
    vendor/motorola/spyder/lib/libmot_led.so:system/lib/libmot_led.so \
    vendor/motorola/spyder/lib/libpppd_plugin-ril.so:system/lib/libpppd_plugin-ril.so \
    vendor/motorola/spyder/lib/libmetainfo.so:system/lib/libmetainfo.so \
    vendor/motorola/spyder/lib/libContextEnginejni.so:system/lib/libContextEnginejni.so \
    vendor/motorola/spyder/lib/libdlnajni.so:system/lib/libdlnajni.so \
    vendor/motorola/spyder/lib/libacc.so:system/lib/libacc.so \
    vendor/motorola/spyder/lib/libmot_btgatt_jni.so:system/lib/libmot_btgatt_jni.so \
    vendor/motorola/spyder/lib/libexempi.so:system/lib/libexempi.so \
    vendor/motorola/spyder/lib/libopencorehw.so:system/lib/libopencorehw.so \
    vendor/motorola/spyder/lib/libopencore_rtspreg.so:system/lib/libopencore_rtspreg.so \
    vendor/motorola/spyder/lib/libopencore_mp4local.so:system/lib/libopencore_mp4local.so \
    vendor/motorola/spyder/lib/libvoicesearch.so:system/lib/libvoicesearch.so \
    vendor/motorola/spyder/lib/libcaps.so:system/lib/libcaps.so \
    vendor/motorola/spyder/lib/libpkip.so:system/lib/libpkip.so \
    vendor/motorola/spyder/lib/libVendor_ti_omx.so:system/lib/libVendor_ti_omx.so \
    vendor/motorola/spyder/lib/libmoto_ril.so:system/lib/libmoto_ril.so \
    vendor/motorola/spyder/lib/libmot_atcmd_mflex.so:system/lib/libmot_atcmd_mflex.so \
    vendor/motorola/spyder/lib/libmtp_jni.so:system/lib/libmtp_jni.so \
    vendor/motorola/spyder/lib/libOMX.TI.DUCATI1.VIDEO.VP6D.so:system/lib/libOMX.TI.DUCATI1.VIDEO.VP6D.so \
    vendor/motorola/spyder/lib/libmoto_nwif_ril.so:system/lib/libmoto_nwif_ril.so \
    vendor/motorola/spyder/lib/libomx_proxy_common.so:system/lib/libomx_proxy_common.so \
    vendor/motorola/spyder/lib/libopencore_net_support.so:system/lib/libopencore_net_support.so \
    vendor/motorola/spyder/lib/libomx_m4vdec_sharedlibrary.so:system/lib/libomx_m4vdec_sharedlibrary.so \
    vendor/motorola/spyder/lib/libtexture_mem.so:system/lib/libtexture_mem.so \
    vendor/motorola/spyder/lib/libtpa_core.so:system/lib/libtpa_core.so \
    vendor/motorola/spyder/lib/libxmpcore.so:system/lib/libxmpcore.so \
    vendor/motorola/spyder/lib/libsmapi.so:system/lib/libsmapi.so \
    vendor/motorola/spyder/lib/libamcm.so:system/lib/libamcm.so \
    vendor/motorola/spyder/lib/libextdisp.so:system/lib/libextdisp.so \
    vendor/motorola/spyder/lib/libWifiAPHardware.so:system/lib/libWifiAPHardware.so \
    vendor/motorola/spyder/lib/libadkutils.so:system/lib/libadkutils.so \
    vendor/motorola/spyder/lib/libarcsoft.so:system/lib/libarcsoft.so \
    vendor/motorola/spyder/lib/libPhotoEditor.so:system/lib/libPhotoEditor.so \
    vendor/motorola/spyder/lib/libportaljni.so:system/lib/libportaljni.so \
    vendor/motorola/spyder/lib/libjni_nwp.so:system/lib/libjni_nwp.so \
    vendor/motorola/spyder/lib/libmotdb.so:system/lib/libmotdb.so \
    vendor/motorola/spyder/lib/libstagefrighthw.so:system/lib/libstagefrighthw.so \
    vendor/motorola/spyder/lib/libpanorama.so:system/lib/libpanorama.so \
    vendor/motorola/spyder/lib/libipcutils.so:system/lib/libipcutils.so \
    vendor/motorola/spyder/lib/libarcomx_qcelpenc_sharedlibrary.so:system/lib/libarcomx_qcelpenc_sharedlibrary.so \
    vendor/motorola/spyder/lib/libSwypeCore.so:system/lib/libSwypeCore.so \
    vendor/motorola/spyder/lib/libkpilogger.so:system/lib/libkpilogger.so \
    vendor/motorola/spyder/lib/libdataencrypt.so:system/lib/libdataencrypt.so \
    vendor/motorola/spyder/lib/libomx_amrenc_sharedlibrary.so:system/lib/libomx_amrenc_sharedlibrary.so \
    vendor/motorola/spyder/lib/libGoToMeetingJNI.so:system/lib/libGoToMeetingJNI.so 

    #vendor/motorola/spyder/lib/libaudiopolicy_ext.so:system/lib/libaudiopolicy_ext.so \


PRODUCT_COPY_FILES += \
    vendor/motorola/spyder/multiconfig/ap/info:system/multiconfig/ap/info \
    vendor/motorola/spyder/multiconfig/ap/7110/lib/libGoToMeetingJNI.so:system/multiconfig/ap/7110/lib/libGoToMeetingJNI.so \
    vendor/motorola/spyder/multiconfig/ap/7110/app/SocialLocation.apk:system/multiconfig/ap/7110/app/SocialLocation.apk \
    vendor/motorola/spyder/multiconfig/ap/7110/app/GoToMeeting.apk:system/multiconfig/ap/7110/app/GoToMeeting.apk \
    vendor/motorola/spyder/multiconfig/ap/7110/app/NeedForSpeed.apk:system/multiconfig/ap/7110/app/NeedForSpeed.apk \
    vendor/motorola/spyder/multiconfig/ap/7110/app/YouTube.apk:system/multiconfig/ap/7110/app/YouTube.apk \
    vendor/motorola/spyder/multiconfig/ap/7110/default.prop:system/multiconfig/ap/7110/default.prop \
    vendor/motorola/spyder/multiconfig/ap/7110/build.prop:system/multiconfig/ap/7110/build.prop \
    vendor/motorola/spyder/multiconfig/ap/7110/etc/motorola/com.android.providers.settings/secure.mkitso:system/multiconfig/ap/7110/etc/motorola/com.android.providers.settings/secure.mkitso \
    vendor/motorola/spyder/multiconfig/ap/7110/etc/motorola/com.android.providers.settings/system.mkitso:system/multiconfig/ap/7110/etc/motorola/com.android.providers.settings/system.mkitso \
    vendor/motorola/spyder/multiconfig/ap/7110/etc/motorola/com.motorola.android.providers.settings/settings.mkitso:system/multiconfig/ap/7110/etc/motorola/com.motorola.android.providers.settings/settings.mkitso \
    vendor/motorola/spyder/multiconfig/ap/7110/etc/motorola/com.motorola.blur.service.blur/defaults.xml:system/multiconfig/ap/7110/etc/motorola/com.motorola.blur.service.blur/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7110/etc/motorola/comm_drv/mmins_telephony.cfg:system/multiconfig/ap/7110/etc/motorola/comm_drv/mmins_telephony.cfg \
    vendor/motorola/spyder/multiconfig/ap/7110/etc/motorola/com.motorola.cellbroadcast/channel_database.mkitso:system/multiconfig/ap/7110/etc/motorola/com.motorola.cellbroadcast/channel_database.mkitso \
    vendor/motorola/spyder/multiconfig/ap/7110/etc/motorola/com.android.phone/defaults.xml:system/multiconfig/ap/7110/etc/motorola/com.android.phone/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7110/etc/motorola/com.motorola.dataswitch/defaults.xml:system/multiconfig/ap/7110/etc/motorola/com.motorola.dataswitch/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7110/etc/motorola/com.motorola.blur.setup/defaults.xml:system/multiconfig/ap/7110/etc/motorola/com.motorola.blur.setup/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7110/etc/motorola/com.motorola.nabsync/defaults.xml:system/multiconfig/ap/7110/etc/motorola/com.motorola.nabsync/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7110/etc/motorola/com.motorola.blur.datamanager.app/defaults.xml:system/multiconfig/ap/7110/etc/motorola/com.motorola.blur.datamanager.app/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7110/etc/motorola/com.motorola.android.dm.service/databases/dmAccounts.xml:system/multiconfig/ap/7110/etc/motorola/com.motorola.android.dm.service/databases/dmAccounts.xml \
    vendor/motorola/spyder/multiconfig/ap/7110/etc/motorola/com.motorola.blur.home/defaults.xml:system/multiconfig/ap/7110/etc/motorola/com.motorola.blur.home/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7110/etc/motorola/com.motorola.android.fota/flex.mkitso:system/multiconfig/ap/7110/etc/motorola/com.motorola.android.fota/flex.mkitso \
    vendor/motorola/spyder/multiconfig/ap/7110/etc/motorola/com.motorola.im/databases/im_flex_settings.xml:system/multiconfig/ap/7110/etc/motorola/com.motorola.im/databases/im_flex_settings.xml \
    vendor/motorola/spyder/multiconfig/ap/7110/etc/motorola/com.motorola.autocontactimport/defaults.xml:system/multiconfig/ap/7110/etc/motorola/com.motorola.autocontactimport/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7110/etc/motorola/com.motorola.togglewidgets/defaults.xml:system/multiconfig/ap/7110/etc/motorola/com.motorola.togglewidgets/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7110/etc/motorola/com.android.browser/databases/bookmarks.xml:system/multiconfig/ap/7110/etc/motorola/com.android.browser/databases/bookmarks.xml \
    vendor/motorola/spyder/multiconfig/ap/7110/etc/motorola/com.android.browser/defaults.xml:system/multiconfig/ap/7110/etc/motorola/com.android.browser/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7110/etc/motorola/com.motorola.blur.weather/defaults.xml:system/multiconfig/ap/7110/etc/motorola/com.motorola.blur.weather/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7110/etc/motorola/com.motorola.android.AudioEffectSettings/defaults.xml:system/multiconfig/ap/7110/etc/motorola/com.motorola.android.AudioEffectSettings/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7110/etc/motorola/com.motorola.blur.conversations/defaults.xml:system/multiconfig/ap/7110/etc/motorola/com.motorola.blur.conversations/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7110/etc/apns-conf.xml:system/multiconfig/ap/7110/etc/apns-conf.xml \
    vendor/motorola/spyder/multiconfig/ap/7110/etc/bluez/main.conf:system/multiconfig/ap/7110/etc/bluez/main.conf \
    vendor/motorola/spyder/multiconfig/ap/7105/lib/libGoToMeetingJNI.so:system/multiconfig/ap/7105/lib/libGoToMeetingJNI.so \
    vendor/motorola/spyder/multiconfig/ap/7105/app/SocialLocation.apk:system/multiconfig/ap/7105/app/SocialLocation.apk \
    vendor/motorola/spyder/multiconfig/ap/7105/app/GoToMeeting.apk:system/multiconfig/ap/7105/app/GoToMeeting.apk \
    vendor/motorola/spyder/multiconfig/ap/7105/app/NeedForSpeed.apk:system/multiconfig/ap/7105/app/NeedForSpeed.apk \
    vendor/motorola/spyder/multiconfig/ap/7105/app/YouTube.apk:system/multiconfig/ap/7105/app/YouTube.apk \
    vendor/motorola/spyder/multiconfig/ap/7105/default.prop:system/multiconfig/ap/7105/default.prop \
    vendor/motorola/spyder/multiconfig/ap/7105/build.prop:system/multiconfig/ap/7105/build.prop \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/motorola/com.android.providers.settings/secure.mkitso:system/multiconfig/ap/7105/etc/motorola/com.android.providers.settings/secure.mkitso \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/motorola/com.android.providers.settings/system.mkitso:system/multiconfig/ap/7105/etc/motorola/com.android.providers.settings/system.mkitso \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/motorola/com.motorola.android.providers.settings/settings.mkitso:system/multiconfig/ap/7105/etc/motorola/com.motorola.android.providers.settings/settings.mkitso \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/motorola/com.motorola.blur.service.blur/defaults.xml:system/multiconfig/ap/7105/etc/motorola/com.motorola.blur.service.blur/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/motorola/comm_drv/mmins_telephony.cfg:system/multiconfig/ap/7105/etc/motorola/comm_drv/mmins_telephony.cfg \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/motorola/com.motorola.cellbroadcast/channel_database.mkitso:system/multiconfig/ap/7105/etc/motorola/com.motorola.cellbroadcast/channel_database.mkitso \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/motorola/com.android.phone/defaults.xml:system/multiconfig/ap/7105/etc/motorola/com.android.phone/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/motorola/com.motorola.dataswitch/defaults.xml:system/multiconfig/ap/7105/etc/motorola/com.motorola.dataswitch/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/motorola/com.motorola.blur.setup/defaults.xml:system/multiconfig/ap/7105/etc/motorola/com.motorola.blur.setup/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/motorola/com.motorola.nabsync/defaults.xml:system/multiconfig/ap/7105/etc/motorola/com.motorola.nabsync/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/motorola/com.motorola.blur.datamanager.app/defaults.xml:system/multiconfig/ap/7105/etc/motorola/com.motorola.blur.datamanager.app/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/motorola/com.motorola.android.dm.service/databases/dmAccounts.xml:system/multiconfig/ap/7105/etc/motorola/com.motorola.android.dm.service/databases/dmAccounts.xml \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/motorola/com.motorola.blur.home/defaults.xml:system/multiconfig/ap/7105/etc/motorola/com.motorola.blur.home/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/motorola/com.motorola.android.fota/flex.mkitso:system/multiconfig/ap/7105/etc/motorola/com.motorola.android.fota/flex.mkitso \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/motorola/com.motorola.im/databases/im_flex_settings.xml:system/multiconfig/ap/7105/etc/motorola/com.motorola.im/databases/im_flex_settings.xml \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/motorola/com.motorola.blur.email/defaults.xml:system/multiconfig/ap/7105/etc/motorola/com.motorola.blur.email/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/motorola/com.motorola.autocontactimport/defaults.xml:system/multiconfig/ap/7105/etc/motorola/com.motorola.autocontactimport/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/motorola/com.motorola.togglewidgets/defaults.xml:system/multiconfig/ap/7105/etc/motorola/com.motorola.togglewidgets/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/motorola/com.android.browser/databases/bookmarks.xml:system/multiconfig/ap/7105/etc/motorola/com.android.browser/databases/bookmarks.xml \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/motorola/com.android.browser/defaults.xml:system/multiconfig/ap/7105/etc/motorola/com.android.browser/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/motorola/com.motorola.blur.weather/defaults.xml:system/multiconfig/ap/7105/etc/motorola/com.motorola.blur.weather/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/motorola/com.motorola.android.AudioEffectSettings/defaults.xml:system/multiconfig/ap/7105/etc/motorola/com.motorola.android.AudioEffectSettings/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/motorola/com.motorola.blur.conversations/defaults.xml:system/multiconfig/ap/7105/etc/motorola/com.motorola.blur.conversations/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/apns-conf.xml:system/multiconfig/ap/7105/etc/apns-conf.xml \
    vendor/motorola/spyder/multiconfig/ap/7105/etc/bluez/main.conf:system/multiconfig/ap/7105/etc/bluez/main.conf \
    vendor/motorola/spyder/multiconfig/ap/7006/lib/libGoToMeetingJNI.so:system/multiconfig/ap/7006/lib/libGoToMeetingJNI.so \
    vendor/motorola/spyder/multiconfig/ap/7006/app/SocialLocation.apk:system/multiconfig/ap/7006/app/SocialLocation.apk \
    vendor/motorola/spyder/multiconfig/ap/7006/app/GoToMeeting.apk:system/multiconfig/ap/7006/app/GoToMeeting.apk \
    vendor/motorola/spyder/multiconfig/ap/7006/app/BILD.apk:system/multiconfig/ap/7006/app/BILD.apk \
    vendor/motorola/spyder/multiconfig/ap/7006/app/NeedForSpeed.apk:system/multiconfig/ap/7006/app/NeedForSpeed.apk \
    vendor/motorola/spyder/multiconfig/ap/7006/app/Kindle.apk:system/multiconfig/ap/7006/app/Kindle.apk \
    vendor/motorola/spyder/multiconfig/ap/7006/app/YouTube.apk:system/multiconfig/ap/7006/app/YouTube.apk \
    vendor/motorola/spyder/multiconfig/ap/7006/default.prop:system/multiconfig/ap/7006/default.prop \
    vendor/motorola/spyder/multiconfig/ap/7006/build.prop:system/multiconfig/ap/7006/build.prop \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/motorola/com.android.providers.settings/secure.mkitso:system/multiconfig/ap/7006/etc/motorola/com.android.providers.settings/secure.mkitso \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/motorola/com.android.providers.settings/system.mkitso:system/multiconfig/ap/7006/etc/motorola/com.android.providers.settings/system.mkitso \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/motorola/com.motorola.android.providers.settings/settings.mkitso:system/multiconfig/ap/7006/etc/motorola/com.motorola.android.providers.settings/settings.mkitso \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/motorola/com.motorola.blur.service.blur/defaults.xml:system/multiconfig/ap/7006/etc/motorola/com.motorola.blur.service.blur/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/motorola/comm_drv/mmins_telephony.cfg:system/multiconfig/ap/7006/etc/motorola/comm_drv/mmins_telephony.cfg \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/motorola/com.motorola.cellbroadcast/channel_database.mkitso:system/multiconfig/ap/7006/etc/motorola/com.motorola.cellbroadcast/channel_database.mkitso \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/motorola/com.android.phone/defaults.xml:system/multiconfig/ap/7006/etc/motorola/com.android.phone/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/motorola/com.motorola.dataswitch/defaults.xml:system/multiconfig/ap/7006/etc/motorola/com.motorola.dataswitch/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/motorola/com.motorola.blur.setup/defaults.xml:system/multiconfig/ap/7006/etc/motorola/com.motorola.blur.setup/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/motorola/com.motorola.nabsync/defaults.xml:system/multiconfig/ap/7006/etc/motorola/com.motorola.nabsync/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/motorola/com.motorola.blur.datamanager.app/defaults.xml:system/multiconfig/ap/7006/etc/motorola/com.motorola.blur.datamanager.app/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/motorola/com.motorola.android.dm.service/databases/dmAccounts.xml:system/multiconfig/ap/7006/etc/motorola/com.motorola.android.dm.service/databases/dmAccounts.xml \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/motorola/com.motorola.blur.home/defaults.xml:system/multiconfig/ap/7006/etc/motorola/com.motorola.blur.home/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/motorola/com.motorola.android.fota/flex.mkitso:system/multiconfig/ap/7006/etc/motorola/com.motorola.android.fota/flex.mkitso \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/motorola/com.motorola.im/databases/im_flex_settings.xml:system/multiconfig/ap/7006/etc/motorola/com.motorola.im/databases/im_flex_settings.xml \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/motorola/com.motorola.blur.email/defaults.xml:system/multiconfig/ap/7006/etc/motorola/com.motorola.blur.email/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/motorola/com.motorola.autocontactimport/defaults.xml:system/multiconfig/ap/7006/etc/motorola/com.motorola.autocontactimport/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/motorola/com.motorola.togglewidgets/defaults.xml:system/multiconfig/ap/7006/etc/motorola/com.motorola.togglewidgets/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/motorola/com.android.browser/databases/bookmarks.xml:system/multiconfig/ap/7006/etc/motorola/com.android.browser/databases/bookmarks.xml \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/motorola/com.android.browser/defaults.xml:system/multiconfig/ap/7006/etc/motorola/com.android.browser/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/motorola/com.motorola.blur.weather/defaults.xml:system/multiconfig/ap/7006/etc/motorola/com.motorola.blur.weather/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/motorola/com.motorola.android.AudioEffectSettings/defaults.xml:system/multiconfig/ap/7006/etc/motorola/com.motorola.android.AudioEffectSettings/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/motorola/com.motorola.blur.conversations/defaults.xml:system/multiconfig/ap/7006/etc/motorola/com.motorola.blur.conversations/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/amazon-kindle.properties:system/multiconfig/ap/7006/etc/amazon-kindle.properties \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/apns-conf.xml:system/multiconfig/ap/7006/etc/apns-conf.xml \
    vendor/motorola/spyder/multiconfig/ap/7006/etc/bluez/main.conf:system/multiconfig/ap/7006/etc/bluez/main.conf \
    vendor/motorola/spyder/multiconfig/ap/7116/lib/libGoToMeetingJNI.so:system/multiconfig/ap/7116/lib/libGoToMeetingJNI.so \
    vendor/motorola/spyder/multiconfig/ap/7116/app/SocialLocation.apk:system/multiconfig/ap/7116/app/SocialLocation.apk \
    vendor/motorola/spyder/multiconfig/ap/7116/app/GoToMeeting.apk:system/multiconfig/ap/7116/app/GoToMeeting.apk \
    vendor/motorola/spyder/multiconfig/ap/7116/app/NeedForSpeed.apk:system/multiconfig/ap/7116/app/NeedForSpeed.apk \
    vendor/motorola/spyder/multiconfig/ap/7116/app/Kindle.apk:system/multiconfig/ap/7116/app/Kindle.apk \
    vendor/motorola/spyder/multiconfig/ap/7116/app/YouTube.apk:system/multiconfig/ap/7116/app/YouTube.apk \
    vendor/motorola/spyder/multiconfig/ap/7116/default.prop:system/multiconfig/ap/7116/default.prop \
    vendor/motorola/spyder/multiconfig/ap/7116/build.prop:system/multiconfig/ap/7116/build.prop \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/motorola/com.android.providers.settings/secure.mkitso:system/multiconfig/ap/7116/etc/motorola/com.android.providers.settings/secure.mkitso \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/motorola/com.android.providers.settings/system.mkitso:system/multiconfig/ap/7116/etc/motorola/com.android.providers.settings/system.mkitso \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/motorola/com.motorola.android.providers.settings/settings.mkitso:system/multiconfig/ap/7116/etc/motorola/com.motorola.android.providers.settings/settings.mkitso \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/motorola/com.motorola.blur.service.blur/defaults.xml:system/multiconfig/ap/7116/etc/motorola/com.motorola.blur.service.blur/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/motorola/comm_drv/mmins_cust_emergency_number.hs:system/multiconfig/ap/7116/etc/motorola/comm_drv/mmins_cust_emergency_number.hs \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/motorola/comm_drv/mmins_cust_emergency_number.cfg:system/multiconfig/ap/7116/etc/motorola/comm_drv/mmins_cust_emergency_number.cfg \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/motorola/comm_drv/mmins_telephony.cfg:system/multiconfig/ap/7116/etc/motorola/comm_drv/mmins_telephony.cfg \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/motorola/com.motorola.cellbroadcast/channel_database.mkitso:system/multiconfig/ap/7116/etc/motorola/com.motorola.cellbroadcast/channel_database.mkitso \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/motorola/com.android.phone/defaults.xml:system/multiconfig/ap/7116/etc/motorola/com.android.phone/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/motorola/com.motorola.dataswitch/defaults.xml:system/multiconfig/ap/7116/etc/motorola/com.motorola.dataswitch/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/motorola/com.motorola.blur.setup/defaults.xml:system/multiconfig/ap/7116/etc/motorola/com.motorola.blur.setup/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/motorola/com.motorola.nabsync/defaults.xml:system/multiconfig/ap/7116/etc/motorola/com.motorola.nabsync/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/motorola/com.motorola.blur.datamanager.app/defaults.xml:system/multiconfig/ap/7116/etc/motorola/com.motorola.blur.datamanager.app/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/motorola/com.motorola.android.dm.service/databases/dmAccounts.xml:system/multiconfig/ap/7116/etc/motorola/com.motorola.android.dm.service/databases/dmAccounts.xml \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/motorola/com.motorola.blur.home/defaults.xml:system/multiconfig/ap/7116/etc/motorola/com.motorola.blur.home/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/motorola/com.motorola.android.fota/flex.mkitso:system/multiconfig/ap/7116/etc/motorola/com.motorola.android.fota/flex.mkitso \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/motorola/com.motorola.im/databases/im_flex_settings.xml:system/multiconfig/ap/7116/etc/motorola/com.motorola.im/databases/im_flex_settings.xml \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/motorola/com.motorola.autocontactimport/defaults.xml:system/multiconfig/ap/7116/etc/motorola/com.motorola.autocontactimport/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/motorola/com.motorola.togglewidgets/defaults.xml:system/multiconfig/ap/7116/etc/motorola/com.motorola.togglewidgets/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/motorola/com.android.browser/databases/bookmarks.xml:system/multiconfig/ap/7116/etc/motorola/com.android.browser/databases/bookmarks.xml \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/motorola/com.android.browser/defaults.xml:system/multiconfig/ap/7116/etc/motorola/com.android.browser/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/motorola/com.motorola.blur.weather/defaults.xml:system/multiconfig/ap/7116/etc/motorola/com.motorola.blur.weather/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/motorola/com.motorola.android.AudioEffectSettings/defaults.xml:system/multiconfig/ap/7116/etc/motorola/com.motorola.android.AudioEffectSettings/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/motorola/com.motorola.blur.conversations/defaults.xml:system/multiconfig/ap/7116/etc/motorola/com.motorola.blur.conversations/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/amazon-kindle.properties:system/multiconfig/ap/7116/etc/amazon-kindle.properties \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/apns-conf.xml:system/multiconfig/ap/7116/etc/apns-conf.xml \
    vendor/motorola/spyder/multiconfig/ap/7116/etc/bluez/main.conf:system/multiconfig/ap/7116/etc/bluez/main.conf \
    vendor/motorola/spyder/multiconfig/ap/backup/app/YouTube.apk:system/multiconfig/ap/backup/app/YouTube.apk \
    vendor/motorola/spyder/multiconfig/ap/backup/build.prop:system/multiconfig/ap/backup/build.prop \
    vendor/motorola/spyder/multiconfig/ap/backup/etc/motorola/com.motorola.blur.service.blur/defaults.xml:system/multiconfig/ap/backup/etc/motorola/com.motorola.blur.service.blur/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/backup/etc/motorola/com.motorola.blur.home/defaults.xml:system/multiconfig/ap/backup/etc/motorola/com.motorola.blur.home/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/backup/etc/motorola/com.motorola.blur.conversations/defaults.xml:system/multiconfig/ap/backup/etc/motorola/com.motorola.blur.conversations/defaults.xml \
    vendor/motorola/spyder/multiconfig/ap/backup/etc/apns-conf.xml:system/multiconfig/ap/backup/etc/apns-conf.xml \
    vendor/motorola/spyder/multiconfig/configIdMap.xml:system/multiconfig/configIdMap.xml \
    vendor/motorola/spyder/multiconfig/master-config-id:system/multiconfig/master-config-id \
    vendor/motorola/spyder/multiconfig/bp/info:system/multiconfig/bp/info \
    vendor/motorola/spyder/multiconfig/bp/51/cefs.img:system/multiconfig/bp/51/cefs.img \
    vendor/motorola/spyder/multiconfig/bp/0/cefs.img:system/multiconfig/bp/0/cefs.img \
    vendor/motorola/spyder/multiconfig/bp/7116/cefs.img:system/multiconfig/bp/7116/cefs.img \
    vendor/motorola/spyder/multiconfig/bota/update_config.zip:system/multiconfig/bota/update_config.zip 
    
    
PRODUCT_COPY_FILES += \
    vendor/motorola/spyder/usr/icu/icudt44l.dat:system/usr/icu/icudt44l.dat \
    vendor/motorola/spyder/usr/keychars/kbd_es_es.kcm.bin:system/usr/keychars/kbd_es_es.kcm.bin \
    vendor/motorola/spyder/usr/keychars/aev_abs.kcm.bin:system/usr/keychars/aev_abs.kcm.bin \
    vendor/motorola/spyder/usr/keychars/kbd_gb_basic.kcm.bin:system/usr/keychars/kbd_gb_basic.kcm.bin \
    vendor/motorola/spyder/usr/keychars/kbd_se_basic.kcm.bin:system/usr/keychars/kbd_se_basic.kcm.bin \
    vendor/motorola/spyder/usr/keychars/kbd_us_basic.kcm.bin:system/usr/keychars/kbd_us_basic.kcm.bin \
    vendor/motorola/spyder/usr/keychars/kbd_ca_fr.kcm.bin:system/usr/keychars/kbd_ca_fr.kcm.bin \
    vendor/motorola/spyder/usr/keychars/omap-keypad.kcm.bin:system/usr/keychars/omap-keypad.kcm.bin \
    vendor/motorola/spyder/usr/keychars/kbd_it_basic.kcm.bin:system/usr/keychars/kbd_it_basic.kcm.bin \
    vendor/motorola/spyder/usr/keychars/kbd_pl_basic.kcm.bin:system/usr/keychars/kbd_pl_basic.kcm.bin \
    vendor/motorola/spyder/usr/keychars/kbd_fi_fi.kcm.bin:system/usr/keychars/kbd_fi_fi.kcm.bin \
    vendor/motorola/spyder/usr/keychars/kbd_us_intl.kcm.bin:system/usr/keychars/kbd_us_intl.kcm.bin \
    vendor/motorola/spyder/usr/keychars/kbd_es_basic.kcm.bin:system/usr/keychars/kbd_es_basic.kcm.bin \
    vendor/motorola/spyder/usr/keychars/kbd_fr_basic.kcm.bin:system/usr/keychars/kbd_fr_basic.kcm.bin \
    vendor/motorola/spyder/usr/keychars/usb_keyboard_102_en_us.kcm.bin:system/usr/keychars/usb_keyboard_102_en_us.kcm.bin \
    vendor/motorola/spyder/usr/keychars/evfwd.kcm.bin:system/usr/keychars/evfwd.kcm.bin \
    vendor/motorola/spyder/usr/keychars/kbd_nl_basic.kcm.bin:system/usr/keychars/kbd_nl_basic.kcm.bin \
    vendor/motorola/spyder/usr/keychars/kbd_de_basic.kcm.bin:system/usr/keychars/kbd_de_basic.kcm.bin \
    vendor/motorola/spyder/usr/keychars/kbd_no_basic.kcm.bin:system/usr/keychars/kbd_no_basic.kcm.bin \
    vendor/motorola/spyder/usr/keychars/kbd_dk_basic.kcm.bin:system/usr/keychars/kbd_dk_basic.kcm.bin \
    vendor/motorola/spyder/usr/keychars/qwerty.kcm.bin:system/usr/keychars/qwerty.kcm.bin \
    vendor/motorola/spyder/usr/keychars/kbd_latam_basic.kcm.bin:system/usr/keychars/kbd_latam_basic.kcm.bin \
    vendor/motorola/spyder/usr/keychars/qwerty2.kcm.bin:system/usr/keychars/qwerty2.kcm.bin \
    vendor/motorola/spyder/usr/keychars/kbd_fi_basic.kcm.bin:system/usr/keychars/kbd_fi_basic.kcm.bin \
    vendor/motorola/spyder/usr/keychars/kbd_br_abnt2.kcm.bin:system/usr/keychars/kbd_br_abnt2.kcm.bin \
    vendor/motorola/spyder/usr/keychars/kbd_pt_basic.kcm.bin:system/usr/keychars/kbd_pt_basic.kcm.bin \
    vendor/motorola/spyder/usr/keychars/kbd_gr_basic.kcm.bin:system/usr/keychars/kbd_gr_basic.kcm.bin \
    vendor/motorola/spyder/usr/keylayout/usb_keyboard_102_en_us.kl:system/usr/keylayout/usb_keyboard_102_en_us.kl 
    

PRODUCT_COPY_FILES += \
    vendor/motorola/spyder/xbin/drm1_func_test:system/xbin/drm1_func_test \
    vendor/motorola/spyder/xbin/ssmgrd:system/xbin/ssmgrd \

